spring.application.name=UserService
spring.datasource.url=jdbc:postgresql://localhost:5432/usersdb
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=postgres
spring.datasource.password=rahul5264
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

#server.servlet.context-path=/users
jwt.secretKey=W+CR9753CIqsRUH46OhUz0FABZ/iCjhm3hr9r95p9QUFcnSJjRm80jnddvyvmQf1BE3mRRhKSvQhVQvKkGpWNA==
eureka.client.service-url.defaultZone=http://localhost:8761/eureka